### ISSUE TITLE
File format is similar to YAML

### ISSUE THREAD

**Issue by hhzl** [lfkeitel/quizzer#8]
The file format close to [YAML](http://yaml.org/)

http://yaml.org/spec/1.2/spec.html

Libraries for different languages: [YAML](http://yaml.org/)

Elements used
- list (array) as a sequence done with a dash
- hashes/dictionaries/maps done with` {four spaces} key: value`

````YAML
---
meta:
    quizzer: 0.1.0
    title: something
    author: someone
questions:
-
    question: What is C++++?
    type: flashcard
    answer: C#
-
    question: What is the distance from the earth to the sun?
    type: flashcard
    answer: 150 million kilometers
-    
    question: Which is the correct answer of 2+2?
    type: multiplechoice
    answer: b
    a: 5
    b: 4
    c: 7
    d: 2
-
    question: Which is the correct answer of 2+3?
    type: multiplechoice
    answer: a
    a: 5
    b: 4
    c: 7
    d: 2
````

converted to [JSON](www.json.org) with [this](https://www.json2yaml.com/) for example.

````JSON
{
  "meta": {
    "quizzer": "0.1.0",
    "title": "something",
    "author": "someone"
  },
  "questions": [
    {
      "question": "What is C++++?",
      "type": "flashcard",
      "answer": "C#"
    },
    {
      "question": "What is the distance from the earth to the sun?",
      "type": "flashcard",
      "answer": "150 million kilometers"
    },
    {
      "question": "Which is the correct answer of 2+2?",
      "type": "multiplechoice",
      "answer": "b",
      "a": 5,
      "b": 4,
      "c": 7,
      "d": 2
    },
    {
      "question": "Which is the correct answer of 2+3?",
      "type": "multiplechoice",
      "answer": "a",
      "a": 5,
      "b": 4,
      "c": 7,
      "d": 2
    }
  ]
}
````

or XML, done with [this](http://www.utilities-online.info/xmltojson)
````xml
<?xml version="1.0" encoding="UTF-8" ?>
	<meta>
		<quizzer>0.1.0</quizzer>
		<title>something</title>
		<author>someone</author>
	</meta>
	<questions>
		<question>What is C++++?</question>
		<type>flashcard</type>
		<answer>C#</answer>
	</questions>
	<questions>
		<question>What is the distance from the earth to the sun?</question>
		<type>flashcard</type>
		<answer>150 million kilometers</answer>
	</questions>
	<questions>
		<question>Which is the correct answer of 2+2?</question>
		<type>multiplechoice</type>
		<answer>b</answer>
		<a>5</a>
		<b>4</b>
		<c>7</c>
		<d>2</d>
	</questions>
	<questions>
		<question>Which is the correct answer of 2+3?</question>
		<type>multiplechoice</type>
		<answer>a</answer>
		<a>5</a>
		<b>4</b>
		<c>7</c>
		<d>2</d>
	</questions>
````

**Comment by lfkeitel** [comment]
The file format was designed to be as minimal as possible. Also, at the time I didn't want an extra library in the project. For now I intend to keep the current custom file format. XML is too verbose and clunky, and I simply don't like YAML. JSON could be used since the file itself isn't intended to be edited manually. If a markup language were to be used, I'd use [TOML](https://github.com/toml-lang/toml) instead with [this library](https://github.com/paiden/Nett).

Is there a particular need to change the format? Was there something you wanted to do with file that you can't without it being converted?

**Comment by hhzl** [comment]
Reason for having relying on a known format like JSON, XML, YAML or TOML is that it is possible to import existing content.

https://github.com/toml-lang

What is the function of the SQLite database?


````TOML
+++
[meta]
quizzer = "0.1.0"
title = "something"
author = "someone"
[[questions]]
question = "What is C++++?"
type = "flashcard"
answer = "C#"
[[questions]]
question = "What is the distance from the earth to the sun?"
type = "flashcard"
answer = "150 million kilometers"
[[questions]]
question = "Which is the correct answer of 2+2?"
type = "multiplechoice"
answer = "b"
a = 5
b = 4
c = 7
d = 2
[[questions]]
question = "Which is the correct answer of 2+3?"
type = "multiplechoice"
answer = "a"
a = 5
b = 4
c = 7
d = 2
+++
````
